- name: Ensure workspace is there
  file:
    path: "{{ pi_workspace }}"
    state: directory

- name: Checkout wiringPi
  git:
    repo: "{{ wiring_pi_repo }}"
    dest: "{{ pi_workspace }}/{{ wiring_pi_name }}"
    update: yes
    register: wiring_pi_checkout

- name: Build wiringPi
  shell: bash build
  args:
    chdir: "{{ pi_workspace }}/{{ wiring_pi_name }}"
  when: wiring_pi_checkout.changed

- name: Checkout raspberry-remote
  git:
    repo: "{{ raspberry_remote_repo }}"
    dest: "{{ pi_workspace }}/{{ raspberry_remote_name }}"
    update: yes
  register: raspberry_remote_checkout

- name: Build raspberry-remote
  shell: make send
  args:
    chdir: "{{ pi_workspace }}/{{ raspberry_remote_name }}"
  when: raspberry_remote_checkout.changed

- name: Make send executable
  file:
    path="{{ pi_workspace }}/{{ raspberry_remote_name }}/send"
    mode=0755

- name: Symlink send command
  file:
    src="{{ pi_workspace }}/{{ raspberry_remote_name }}/send"
    dest="/usr/bin/send"
    state=link
