- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - alsa-utils
    - bluez
    - bluez-tools
    - pulseaudio-module-bluetooth
    - python-gobject
    - python-gobject-2

# sudo reboot ?
- name: User Management
  shell: usermod -a -G lp pi && usermod -a -G pulse-access,audio root && adduser pi pulse-access

- name: Add Pulse resample-method
  lineinfile:
    dest: /etc/pulse/daemon.conf
    regexp: ^resample-method
    line: resample-method = trivial

- name: Add Pulse addons
  copy:
    dest: /etc/pulse/system.pa
    src: system.pa

- name: Start pulseaudio
  shell: if pgrep "pulseaudio" > /dev/null; then echo "Running"; else pulseaudio -D; fi
  register: pulse_running
  changed_when: pulse_running.changed and pulse_running.stdout="Running"

- name: Change Audio-Output to Audiojack
  shell: amixer cset numid=3 1

- name: Change Volume
  shell: amixer set Master 100% && pacmd set-sink-volume 0 65535

- name: Add Bluetooth audio conf
  copy:
    dest: /etc/bluetooth/audio.conf
    src: audio.conf

- name: Add Bluetooth main conf
  copy:
    dest: /etc/bluetooth/main.conf
    src: main.conf

- name: Configure Bluetooth dongle
  copy:
    dest: "/var/lib/bluetooth/{{ BLUETOOTH_MAC }}/settings"
    src: settings

- name: Restart machine
  command: shutdown -r now "Ansible triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: Waiting for server to come back
  local_action:
    wait_for host={{ inventory_hostname }}
             state=started
  sudo: false
