- name: Restart machine
  command: shutdown -r now "Ansible triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: Waiting for server to come back
  local_action:
    wait_for host={{ inventory_hostname }}
             state=started
  become: false
