---
  # Build after https://github.com/agent4788/SHC_Framework/wiki/Raspberry-Pi

- name: Install Webserver packages
  package:
    name: git
    state: latest
  with_items:
    - php5-common
    - php5-cgi
    - php5-cli
    - php-apc
    - apache2
    - libapache2-mod-php5
    - redis-server
    - php5-redis
    - php5-dev

# Todo Falls Raspbian Jessie (Light) verwendet wird, muss der DocumentRoot des Webserver angepasst werden. Dazu in der Datei /etc/apache2/sites-available/000-default.conf die Zeile 12 mit folgendem Eintrag ersetzen und den Webserver neu starten
#
# /var/www
# sudo service apache2 restart

- name: Install php-redis
  git:
    repo: https://github.com/phpredis/phpredis.git
    dest: "{{ phpredis_install_folder }}"
    update: yes
  register: php-redis

- name: Configure phpredis
  shell: ./configure
  args:
    chdir: "{{ phpredis_install_folder }}"
  when: php-redis.changed

- name: Make phpredis
  shell: make
  args:
    chdir: "{{ phpredis_install_folder }}"
  when: php-redis.changed

- name: Install phpredis
  shell: make install
  args:
    chdir: "{{ phpredis_install_folder }}"
  when: php-redis.changed

- name: Create ramdisk
  lineinfile:
    dest: /etc/fstab
    regexp: "tmpfs         /var/www/shc/rwf/data/cache"
    line: "tmpfs         /var/www/shc/rwf/data/cache      tmpfs   nosuid,size=5M         0       0"
    validate: "mount -fav"
